// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using XLab.Data.Context;
using XLab.Data.Models;

namespace XLab.Data.Context.Configurations
{
    public partial class EnrolmentConfiguration : IEntityTypeConfiguration<Enrolment>
    {
        public void Configure(EntityTypeBuilder<Enrolment> entity)
        {
            entity.ToTable("Enrolment");

            entity.Property(e => e.EnrolmentDate).HasColumnType("datetime");

            entity.HasOne(d => d.Course)
                .WithMany(p => p.Enrolments)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Enrolment_Course");

            entity.HasOne(d => d.Student)
                .WithMany(p => p.Enrolments)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Enrolment_Student");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Enrolment> entity);
    }
}
