// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using XLab.Data.Context;
using XLab.Data.Models;

namespace XLab.Data.Context.Configurations
{
    public partial class ExamStudentAnwerConfiguration : IEntityTypeConfiguration<ExamStudentAnwer>
    {
        public void Configure(EntityTypeBuilder<ExamStudentAnwer> entity)
        {
            entity.HasOne(d => d.Answer)
                .WithMany(p => p.ExamStudentAnwers)
                .HasForeignKey(d => d.AnswerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExamStudentAnwers_QuestionAnswers");

            entity.HasOne(d => d.Exam)
                .WithMany(p => p.ExamStudentAnwers)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExamStudentAnwers_Exam");

            entity.HasOne(d => d.Question)
                .WithMany(p => p.ExamStudentAnwers)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExamStudentAnwers_Question");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ExamStudentAnwer> entity);
    }
}
