// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace XLab.Data.Models
{
    public partial class Course
    {
        public Course()
        {
            Enrolments = new HashSet<Enrolment>();
            Exams = new HashSet<Exam>();
            Questions = new HashSet<Question>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int InstructorId { get; set; }
        public int TopicId { get; set; }
        public int? ExamDuration { get; set; }
        public int? QuestionsCount { get; set; }
        public int? SuccessRate { get; set; }

        public virtual Instructor Instructor { get; set; }
        public virtual Topic InstructorNavigation { get; set; }
        public virtual ICollection<Enrolment> Enrolments { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}