// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace XLab.Data.Models
{
    public partial class Exam
    {
        public Exam()
        {
            ExamQuestions = new HashSet<ExamQuestion>();
            ExamStudentAnwers = new HashSet<ExamStudentAnwer>();
        }

        public int Id { get; set; }
        public int CourseId { get; set; }
        public int StudentId { get; set; }
        public int Grad { get; set; }
        public int? StudentGrad { get; set; }
        public bool IsCompleted { get; set; }
        public DateTime ExamDate { get; set; }

        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }
        public virtual ICollection<ExamStudentAnwer> ExamStudentAnwers { get; set; }
    }
}