// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace XLab.Data.Models
{
    public partial class QuestionAnswer
    {
        public QuestionAnswer()
        {
            ExamStudentAnwers = new HashSet<ExamStudentAnwer>();
        }

        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string Answer { get; set; }
        public bool CorrectAnswer { get; set; }

        public virtual Question Question { get; set; }
        public virtual ICollection<ExamStudentAnwer> ExamStudentAnwers { get; set; }
    }
}