// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace XLab.Data.Models
{
    public partial class Student
    {
        public Student()
        {
            Enrolments = new HashSet<Enrolment>();
            Exams = new HashSet<Exam>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int? Building { get; set; }
        public DateTime? Dob { get; set; }
        public int DepartmentId { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<Enrolment> Enrolments { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
    }
}